### ISSUE TITLE
Add Github icon and include the link in website

### ISSUE THREAD

**Issue by Vijaykv5** [ZeroOctave/ZeroOctave.github.io#80]
Add a Github link in the website footer
![Capture](https://user-images.githubusercontent.com/94985341/221360047-adf28ed6-dbf5-4cf4-b2e6-81e9acf18ec1.PNG)

**Comment by DhirajGilda** [comment]
i would like to contribute to this issue @Astrodevil should i create pull request directly as i am a beginner to open source or i should wait

**Comment by DhirajGilda** [comment]
i have done that in the local branch @Astrodevil  waiting for approval to create pull request

**Comment by Vijaykv5** [comment]
> i would like to contribute to this issue @Astrodevil should i create pull request directly as i am a beginner to open source or i should wait

Create a PR man !
